### ISSUE TITLE
Owned NFTs not loaded when account has big nr. of tokens (balance)

### ISSUE THREAD

**Issue by remy0079** [holaplex/holaplex#289]
If there are a big number of tokens in users wallet, loading of NFTs fail. 

bn.js:6 Uncaught (in promise) Error: Number can only safely store up to 53 bits
    at r (bn.js:6:21)
    at _t.o.toNumber (bn.js:547:7)
    at t.loadMetadataForUsers (loadAccounts.js:48:46)
    at index.tsx:38:35
    at l (runtime.js:45:40)
    at Generator._invoke (runtime.js:274:22)
    at Generator.P.forEach.e.<computed> [as next] (runtime.js:97:21)

**Comment by dandlezzz** [comment]
Mind posting the wallet address that caused the problem?

**Comment by remy0079** [comment]
22LKscJkbD5zKidhLbiK2UkfhTeQt8FZrZyMpegptsW7
Workaround is to move tokens into another account
